import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Inter } from 'next/font/google';
import Script from 'next/script';
import './globals.css';

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = useMessages();
  return (
    <html suppressHydrationWarning={true} lang={locale}>
      <head>
        <Script
          async
          src='https://www.googletagmanager.com/gtag/js?id=G-RG9WVXCKJ3'></Script>
        <Script id='google-analytics'>
          {`  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RG9WVXCKJ3');`}
        </Script>
      </head>
      <body suppressHydrationWarning={true} className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
